name: Smart PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

permissions:
  statuses: write
  contents: read
  pull-requests: write
  issues: write

# Define common configuration as workflow-level environment variables
env:
  IGNORED_FILES: |
    docs/**
    *.md
    .gitignore
    scripts/**

jobs:
  # Job 1: Check if test is required based on file changes
  check-if-test-required:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    outputs:
      test-required: ${{ steps.check-files.outputs.test-required }}
      pr-number: ${{ github.event.pull_request.number }}
      head-sha: ${{ github.event.pull_request.head.sha }}
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files_ignore: ${{ env.IGNORED_FILES }}

      - name: Set commit status based on requirement
        uses: myrotvorets/set-commit-status-action@v1.1.7
        with:
          sha: ${{ github.event.pull_request.head.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ steps.changed-files.outputs.any_changed == 'true' && 'pending' || 'success' }}
          context: 'Special Test Check'
          description: ${{ steps.changed-files.outputs.any_changed == 'true' && 'Test required - comment "run test" to execute' || 'Test not required - no relevant files changed' }}

  # Job 2: Run actual test when comment is made
  run-test-on-comment:
    if: github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, 'run test')
    runs-on: ubuntu-latest
    timeout-minutes: 50
    steps:
      - name: Get branch of PR
        uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch

      - name: Set latest commit status as pending
        uses: myrotvorets/set-commit-status-action@v1.1.7
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending
          context: 'Special Test Check'
          description: 'Running tests...'

      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files_ignore: ${{ env.IGNORED_FILES }}

      - name: Count lines in src/Main.kt
        id: count-lines
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          if [ -f "src/Main.kt" ]; then
            LINE_COUNT=$(wc -l < src/Main.kt)
            echo "Line count in src/Main.kt: $LINE_COUNT"
            echo "line-count=$LINE_COUNT" >> $GITHUB_OUTPUT
          
            if [ $LINE_COUNT -gt 100 ]; then
              echo "❌ Test FAILED: src/Main.kt has $LINE_COUNT lines (exceeds 100 line limit)"
              echo "test-result=failure" >> $GITHUB_OUTPUT
              echo "test-message=❌ Test FAILED: src/Main.kt has $LINE_COUNT lines (exceeds 100 line limit)" >> $GITHUB_OUTPUT
            else
              echo "✅ Test PASSED: src/Main.kt has $LINE_COUNT lines (within 100 line limit)"
              echo "test-result=success" >> $GITHUB_OUTPUT
              echo "test-message=✅ Test PASSED: src/Main.kt has $LINE_COUNT lines (within 100 line limit)" >> $GITHUB_OUTPUT
            fi
          else
            echo "❌ Test FAILED: src/Main.kt not found"
            echo "test-result=failure" >> $GITHUB_OUTPUT
            echo "test-message=❌ Test FAILED: src/Main.kt not found" >> $GITHUB_OUTPUT
          fi

      - name: Send test result comment
        if: always() && steps.changed-files.outputs.any_changed == 'true'
        uses: mshick/add-pr-comment@v2
        with:
          refresh-message-position: true
          message: |
            ## Smart PR Check Results 🎯
            
            **Commit:** [${{ steps.comment-branch.outputs.head_sha }}](https://github.com/${{ github.repository }}/commit/${{ steps.comment-branch.outputs.head_sha }})
            
            **Test Result:** ${{ steps.count-lines.outputs.test-message }}
            
            **Details:**
            - File checked: `src/Main.kt`
            - Line count: ${{ steps.count-lines.outputs.line-count || 'N/A' }}
            - Limit: 100 lines
            
            [View full workflow run →](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

      - name: Send skip comment if test not required
        if: always() && steps.changed-files.outputs.any_changed == 'false'
        uses: mshick/add-pr-comment@v2
        with:
          refresh-message-position: true
          message: |
            ## Smart PR Check Results 🎯
            
            **Commit:** [${{ steps.comment-branch.outputs.head_sha }}](https://github.com/${{ github.repository }}/commit/${{ steps.comment-branch.outputs.head_sha }})
            
            **Result:** ⏭️ **Test Skipped** - Only ignored files were changed
            
            No relevant files were modified that require testing.

      - name: Set final commit status
        if: always()
        uses: myrotvorets/set-commit-status-action@v1.1.7
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ steps.changed-files.outputs.any_changed == 'false' && 'success' || steps.count-lines.outputs.test-result }}
          context: 'Special Test Check'
          description: ${{ steps.changed-files.outputs.any_changed == 'false' && 'Test skipped - no relevant files changed' || steps.count-lines.outputs.test-message }}